import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "Car2Go | About",
  description: "Generated by create next app",
};

export default function About() {
  return (
    <div>About</div>
  )
}
