import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "Car2Go | Contact",
  description: "Generated by create next app",
};

export default function Contact() {
  return (
    <div className='flex justify-center items-center h-screen'>
      Contact
    </div>
  )
}
