import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../globals.css";
import Footer from "@/components/Footer";



const poppins = Poppins({
  subsets: ["latin"],
  weight: "600"
});

export const metadata: Metadata = {
  title: "Car2Go | Home",
  description: "Generated by create next app",
};

export default function CarDetailsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        {children}
        <Footer />
      </body>
    </html>
  );
}